import {
  LayoutDashboard, Users, GraduationCap, UserCircle, School, BookOpen, CalendarDays,
  CalendarClock, ClipboardCheck, FileSpreadsheet, FileText, TrendingUp, PenSquare,
  Megaphone, BarChart3, Settings, ShieldCheck, QrCode, Bell,
} from 'lucide-react'

export const MENUS = {
  admin: [
    { to: '/admin/dashboard', label: 'Dashboard', icon: LayoutDashboard },
    { to: '/admin/students', label: 'Siswa', icon: Users },
    { to: '/admin/teachers', label: 'Guru', icon: GraduationCap },
    { to: '/admin/parents', label: 'Orang Tua', icon: UserCircle },
    { to: '/admin/classes', label: 'Kelas', icon: School },
    { to: '/admin/subjects', label: 'Mata Pelajaran', icon: BookOpen },
    { to: '/admin/academic-years', label: 'Tahun Ajaran', icon: CalendarClock },
    { to: '/admin/calendar', label: 'Kalender Akademik', icon: CalendarDays },
    { to: '/admin/schedules', label: 'Jadwal', icon: CalendarClock },
    { to: '/admin/attendance', label: 'Absensi', icon: ClipboardCheck },
    { to: '/admin/grades', label: 'Nilai', icon: PenSquare },
    { to: '/admin/promotion', label: 'Kenaikan Kelas', icon: TrendingUp },
    { to: '/admin/exams', label: 'Ujian', icon: FileSpreadsheet },
    { to: '/admin/announcements', label: 'Pengumuman', icon: Megaphone },
    { to: '/admin/reports', label: 'Laporan', icon: FileText },
    { to: '/admin/audit-log', label: 'Audit Log', icon: ShieldCheck },
    { to: '/admin/settings', label: 'Pengaturan', icon: Settings },
  ],
  teacher: [
    { to: '/teacher/dashboard', label: 'Dashboard', icon: LayoutDashboard },
    { to: '/teacher/schedules', label: 'Jadwal Mengajar', icon: CalendarClock },
    { to: '/teacher/attendance', label: 'Absensi', icon: ClipboardCheck },
    { to: '/teacher/grades', label: 'Nilai', icon: PenSquare },
    { to: '/teacher/exams', label: 'Jadwal Ujian', icon: FileSpreadsheet },
    { to: '/teacher/announcements', label: 'Pengumuman', icon: Megaphone },
  ],
  homeroom: [
    { to: '/homeroom/dashboard', label: 'Dashboard', icon: LayoutDashboard },
    { to: '/homeroom/students', label: 'Siswa Kelas', icon: Users },
    { to: '/homeroom/attendance', label: 'Absensi', icon: ClipboardCheck },
    { to: '/homeroom/grades', label: 'Nilai', icon: PenSquare },
    { to: '/homeroom/notes', label: 'Catatan Siswa', icon: FileText },
    { to: '/homeroom/report-cards', label: 'Rapor', icon: FileText },
    { to: '/homeroom/promotion', label: 'Kenaikan Kelas', icon: TrendingUp },
  ],
  student: [
    { to: '/student/dashboard', label: 'Dashboard', icon: LayoutDashboard },
    { to: '/student/profile', label: 'Profil', icon: UserCircle },
    { to: '/student/schedule', label: 'Jadwal', icon: CalendarClock },
    { to: '/student/attendance', label: 'Absensi', icon: ClipboardCheck },
    { to: '/student/grades', label: 'Nilai', icon: PenSquare },
    { to: '/student/report-card', label: 'Rapor', icon: FileText },
    { to: '/student/exams', label: 'Jadwal Ujian', icon: FileSpreadsheet },
    { to: '/student/announcements', label: 'Pengumuman', icon: Megaphone },
    { to: '/student/calendar', label: 'Kalender Akademik', icon: CalendarDays },
    { to: '/student/qr', label: 'QR Identitas', icon: QrCode },
  ],
  parent: [
    { to: '/parent/dashboard', label: 'Dashboard', icon: LayoutDashboard },
    { to: '/parent/grades', label: 'Nilai', icon: PenSquare },
    { to: '/parent/report-card', label: 'Rapor', icon: FileText },
    { to: '/parent/attendance', label: 'Absensi', icon: ClipboardCheck },
    { to: '/parent/schedule', label: 'Jadwal', icon: CalendarClock },
    { to: '/parent/exams', label: 'Jadwal Ujian', icon: FileSpreadsheet },
    { to: '/parent/announcements', label: 'Pengumuman', icon: Megaphone },
  ],
}
